json.id visit.id
json.start_date visit.start_date
json.end_date visit.end_date
json.hospital visit.hospital
json.reason visit.reason
json.user_id visit.user_id
json.doctors visit.doctors
json.nurses visit.nurses
json.medications visit.medications
json.procedures visit.procedures
json.questions visit.questions
